#!/usr/bin/env bash


# Cleanup configuration system files.


shopt -s globstar

# Ansible files.
rm -rf ~/.ansible/**/__pycache__
rm -rf ~/.ansible/**/*.pyc
rm -rf ~/.ansible/tmp
rm -rf playbook.yml

# __pycache__ is generated by the Python interpreter while running programs.
rm -rf /usr/local/lib/python3*/**/__pycache__
rm -rf /usr/lib/python3/dist-packages/**/__pycache__
